// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_category_query.sql

package repository

import (
	"context"
)

const registerEmailAndCategory = `-- name: RegisterEmailAndCategory :exec
INSERT INTO email_category (email_id, category_id) VALUES (?, ?)
`

type RegisterEmailAndCategoryParams struct {
	EmailID    int64
	CategoryID int64
}

func (q *Queries) RegisterEmailAndCategory(ctx context.Context, arg RegisterEmailAndCategoryParams) error {
	_, err := q.db.ExecContext(ctx, registerEmailAndCategory, arg.EmailID, arg.CategoryID)
	return err
}
