// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64
	Name      string
	Key       string
	Modseq    int64
	CreatedAt sql.NullTime
}

type Email struct {
	ID        int64
	Seq       int64
	Sender    string
	Subject   string
	EmailDate time.Time
	CreatedAt sql.NullTime
}

type EmailCategory struct {
	EmailID    int64
	CategoryID int64
}
